# Generated by Django 6.0.3 on 2026-03-07 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barrio',
            name='telefono',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
