# Generated by Django 6.0.3 on 2026-03-08 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_barrio_telefono'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoBarrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='contratos/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('barrio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.barrio')),
            ],
        ),
    ]
