# Generated by Django 6.0.3 on 2026-03-11 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_comunicado'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuscripcionBarrio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(default='basico', max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField()),
                ('activo', models.BooleanField(default=True)),
                ('barrio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.barrio')),
            ],
        ),
    ]
