# Generated by Django 6.0.3 on 2026-03-13 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_suscripcionbarrio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='facturas/')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('barrio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.barrio')),
            ],
        ),
    ]
