# Generated by Django 6.0.3 on 2026-03-19 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='propiedad',
            name='contrato',
            field=models.FileField(blank=True, null=True, upload_to='contratos/'),
        ),
    ]
