# Generated by Django 6.0.3 on 2026-03-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_propiedad_contrato'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barrio',
            name='activo',
        ),
        migrations.AddField(
            model_name='barrio',
            name='contrato',
            field=models.FileField(blank=True, null=True, upload_to='contratos/'),
        ),
        migrations.AlterField(
            model_name='barrio',
            name='cbu',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='barrio',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='barrio',
            name='telefono',
            field=models.CharField(max_length=50),
        ),
    ]
