# Generated by Django 6.0.3 on 2026-03-19 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_barrio_activo_barrio_contrato_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barrio',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
