# Generated by Django 6.0.3 on 2026-03-20 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_barrio_fecha_vencimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seguridad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_apellido', models.CharField(max_length=150)),
                ('dni', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
                ('fecha_ingreso', models.DateField()),
                ('foto_dni', models.ImageField(blank=True, null=True, upload_to='dni_seguridad/')),
                ('barrio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.barrio')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso')], max_length=10)),
                ('fecha_hora', models.DateTimeField()),
                ('patente', models.CharField(max_length=20)),
                ('nombre_apellido', models.CharField(max_length=150)),
                ('dni', models.CharField(max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('barrio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.barrio')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.seguridad')),
            ],
        ),
    ]
