# Generated by Django 6.0.3 on 2026-04-06 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_seguridad_movimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='comprobante',
            field=models.URLField(),
        ),
    ]
