# Generated by Django 6.0.3 on 2026-04-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_pago_comprobante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='archivo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
