# Generated by Django 6.0.3 on 2026-04-06 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_factura_archivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoAdelantado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meses', models.JSONField()),
                ('anio', models.IntegerField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('comprobante', models.URLField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente_validacion', 'Pendiente Validación'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente_validacion', max_length=30)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('propiedad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.propiedad')),
            ],
        ),
    ]
