# Generated by Django 6.0.3 on 2026-04-07 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_pagoadelantado'),
    ]

    operations = [
        migrations.AddField(
            model_name='barrio',
            name='banco',
            field=models.CharField(blank=True, default='Banco Nación', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='barrio',
            name='cuit',
            field=models.CharField(blank=True, default='30-12345678-9', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='barrio',
            name='titular_cuenta',
            field=models.CharField(blank=True, default='Asociación Vecinal', max_length=150, null=True),
        ),
    ]
