# Generated by Django 6.0.3 on 2026-04-08 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_barrio_banco_barrio_cuit_barrio_titular_cuenta'),
    ]

    operations = [
        migrations.AddField(
            model_name='barrio',
            name='fecha_inicio_suscripcion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='barrio',
            name='plan',
            field=models.CharField(choices=[('mensual', 'Mensual'), ('semestral', 'Semestral'), ('anual', 'Anual')], default='mensual', max_length=20),
        ),
        migrations.AddField(
            model_name='barrio',
            name='precio_suscripcion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='barrio',
            name='responsable',
            field=models.CharField(blank=True, default='Administrador', max_length=150, null=True),
        ),
        migrations.AlterModelTable(
            name='factura',
            table='facturas',
        ),
    ]
