# Generated by Django 6.0.3 on 2026-04-09 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_barrio_fecha_inicio_suscripcion_barrio_plan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicado',
            name='mensaje',
            field=models.CharField(max_length=500),
        ),
    ]
