# Generated by Django 6.0.3 on 2026-04-09 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_comunicado_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunicado',
            name='fecha_limite',
            field=models.DateField(blank=True, null=True),
        ),
    ]
