# Generated by Django 6.0.3 on 2026-04-09 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_comunicado_fecha_limite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comunicado',
            name='mensaje',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='contratobarrio',
            name='archivo',
            field=models.CharField(max_length=500),
        ),
    ]
